# site settings

title: Rajvi Patel
description: Software Engineer
taglong: Senior Software Engineer
tagshort: Senior Software Engineer
url: https://rajvi-patel-22.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/rajvi-patel-22/rajvi-patel-22.github.io

# author settings

author:
  name: Rajvi Patel
  email: rpate188@asu.edu
photo: /assets/jpg/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
